apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-bff
  template:
    metadata:
      labels:
        app: web-bff
    spec:
      containers:
        - name: web-bff
          image: docker.io/mgperson/web-bff:final8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: BOOK_SERVICE_BASE_URL
              value: "http://book-service:3000"
            - name: CUSTOMER_SERVICE_BASE_URL
              value: "http://customer-service:3000"
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15